apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins-agents
spec:
  serviceAccountName: jenkins-agent
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - "9999999"
    resources:
      limits:
        cpu: "250m"
        memory: "250Mi"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - "9999999"
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
      - name: cache
        mountPath: /workspace/cache
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
  - name: cache
    persistentVolumeClaim:
      claimName: kaniko-images-claim